In [6]:
import pandas as pd
path = r"H:\Python\3Etapa\AnaliseDados\CD2022_Populacao_2010_Compatibilizada_20231222.xlsx"

Carregando o excell com tudo, sem nenhum tipo de alteração, o header serve apenas para cortar as 2 primeiras informações "inuteis"

In [7]:
dado_bruto = pd.read_excel(path, header = 2)
dado_bruto

,Unnamed: 0,UF,COD. UF,COD. MUNIC,NOME DO MUNICÍPIO,População Município 2010\n(Sinopse),População 2010 (Alterações de Limites até 2022)1,População Censo 2022
0,NaN,RO,11.0,15.0,Alta Floresta D'Oeste,24392.0,24392.0,21494.0
1,NaN,RO,11.0,23.0,Ariquemes,90353.0,90353.0,96833.0
2,NaN,RO,11.0,31.0,Cabixi,6313.0,6313.0,5351.0
3,NaN,RO,11.0,49.0,Cacoal,78574.0,78574.0,86887.0
4,NaN,RO,11.0,56.0,Cerejeiras,17029.0,17029.0,15890.0
...,...,...,...,...,...,...,...,...
5569,NaN,DF,53.0,108.0,Brasília,2570160.0,2572159.0,2817381.0
5570,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5571,NaN,Nota: Para o cálculo das taxas de crescimento ...,NaN,NaN,NaN,NaN,NaN,NaN
5572,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5573,NaN,Fonte: IBGE. Diretoria de Pesquisas - DPE - C...,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
dados_trabalhados = dado_bruto.iloc[0:5570,1:]

In [9]:
dados_trabalhados.columns

Index(['UF', 'COD. UF', 'COD. MUNIC', 'NOME DO MUNICÍPIO',
       'População Município 2010\n(Sinopse)',
       'População 2010 (Alterações de Limites até 2022)1',
       'População Censo 2022'],
      dtype='str')

In [16]:
dados_trabalhados["Diferenca"] = (dados_trabalhados["População Censo 2022"]  - dados_trabalhados["População Município 2010\n(Sinopse)"])

In [17]:
dados_trabalhados

,UF,COD. UF,COD. MUNIC,NOME DO MUNICÍPIO,População Município 2010\n(Sinopse),População 2010 (Alterações de Limites até 2022)1,População Censo 2022,Diferenca
0,RO,11.0,15.0,Alta Floresta D'Oeste,24392.0,24392.0,21494.0,-2898.0
1,RO,11.0,23.0,Ariquemes,90353.0,90353.0,96833.0,6480.0
2,RO,11.0,31.0,Cabixi,6313.0,6313.0,5351.0,-962.0
3,RO,11.0,49.0,Cacoal,78574.0,78574.0,86887.0,8313.0
4,RO,11.0,56.0,Cerejeiras,17029.0,17029.0,15890.0,-1139.0
...,...,...,...,...,...,...,...,...
5565,GO,52.0,22005.0,Vianópolis,12548.0,12548.0,14956.0,2408.0
5566,GO,52.0,22054.0,Vicentinópolis,7371.0,7373.0,8768.0,1397.0
5567,GO,52.0,22203.0,Vila Boa,4735.0,4735.0,4215.0,-520.0
5568,GO,52.0,22302.0,Vila Propício,5145.0,5145.0,5815.0,670.0
5569,DF,53.0,108.0,Brasília,2570160.0,2572159.0,2817381.0,247221.0

In [23]:
dados_trabalhados.to_csv("dados_trabalhados.csv", index=False, encoding="utf-8-sig")

In [22]:
dados_trabalhados = dados_trabalhados.sort_values(
    by="Diferenca",
    ascending=False
)
dados_trabalhados

,UF,COD. UF,COD. MUNIC,NOME DO MUNICÍPIO,População Município 2010\n(Sinopse),População 2010 (Alterações de Limites até 2022)1,População Censo 2022,Diferenca
111,AM,13.0,2603.0,Manaus,1802014.0,1802014.0,2063689.0,261675.0
5569,DF,53.0,108.0,Brasília,2570160.0,2572159.0,2817381.0,247221.0
3829,SP,35.0,50308.0,São Paulo,11253503.0,11253503.0,11451999.0,198496.0
3848,SP,35.0,52205.0,Sorocaba,586625.0,586816.0,723682.0,137057.0
5417,GO,52.0,8707.0,Goiânia,1302001.0,1301912.0,1437366.0,135365.0
...,...,...,...,...,...,...,...,...
4931,RS,43.0,14902.0,Porto Alegre,1409351.0,1409351.0,1332845.0,-76506.0
169,PA,15.0,1402.0,Belém,1393399.0,1393399.0,1303403.0,-89996.0
3247,RJ,33.0,4904.0,São Gonçalo,999728.0,999728.0,896744.0,-102984.0
3242,RJ,33.0,4557.0,Rio de Janeiro,6320446.0,6320446.0,6211223.0,-109223.0
2162,BA,29.0,27408.0,Salvador,2675656.0,2675656.0,2417678.0,-257978.0

In [25]:
dados_trabalhados.to_csv("dados_trabalhados.csv", index=False, encoding="utf-8-sig")